### ISSUE TITLE
Iteration plan

### ISSUE THREAD

**Issue by Jvr2022** [xanonDev/pinkcord#36]
Can u create a iteration plan @xanonDev

**Comment by xanonDev** [comment]
iteration plan
And what is that?

**Comment by xanonDev** [comment]
or it doesn't matter anymore I see in the discussion

**Comment by Jvr2022** [comment]
Can u create a more detailed list with commands u want

**Comment by Jvr2022** [comment]
In iteration plan discussion

**Comment by xanonDev** [comment]
I will think more about these commands and write more

**Comment by Jvr2022** [comment]
Hi have u more projects where i can help @xanonDev

**Comment by xanonDev** [comment]
unfortunately not at the moment

**Comment by Jvr2022** [comment]
I through something with spam bots for discord and sms

**Comment by xanonDev** [comment]
two ideas is good, we can make something out of it in the future

**Comment by Jvr2022** [comment]
Remove stale
