### ISSUE TITLE
the rat wont connect to my discord bot although its installed with the token

### ISSUE THREAD

**Issue by bawsuser** [xanonDev/pinkcord#53]
the rat wont connect to my discord bot although its installed with the token

**Comment by Jvr2022** [comment]
What version of pinkcord?

**Comment by bawsuser** [comment]
i used the current repository

**Comment by Jvr2022** [comment]
The current respority version have a bug please use the latest version

**Comment by bawsuser** [comment]
oh okay

**Comment by Jvr2022** [comment]
On the respority I am expertmating with 2.0

**Comment by Jvr2022** [comment]
Let me know if it worked

**Comment by bawsuser** [comment]
nah still seems not to work

**Comment by Jvr2022** [comment]
Can you send logs?

**Comment by bawsuser** [comment]
sorry i might seem a bit dumb but how should i get logs

**Comment by bawsuser** [comment]
discord is not telling anything and on the machine i dont know how to get them

**Comment by Jvr2022** [comment]
Can you let me see screenshots

**Comment by Jvr2022** [comment]
Did you use !h on the bot in dms

**Comment by Jvr2022** [comment]
It is not working in servers

**Comment by bawsuser** [comment]
i tried !h on the bot in discord

**Comment by Jvr2022** [comment]
Is the bot online?

**Comment by Jvr2022** [comment]
Is the cmd still open

**Comment by Jvr2022** [comment]
When it is closed it dont work

**Comment by bawsuser** [comment]
do you mean the setup cmd ? or should i start the .bat in a cmd

**Comment by Jvr2022** [comment]
Pinkcord.py

**Comment by Jvr2022** [comment]
A file that the setup made

**Comment by bawsuser** [comment]
it just says 
![Screenshot from 2024-05-15 20-22-40](https://github.com/xanonDev/pinkcord/assets/49470648/624fc596-4d94-4a17-a281-1619fdd492c3)

**Comment by Jvr2022** [comment]
I look tomorrow into the problem

**Comment by bawsuser** [comment]
i programed a little discord bot myself and besides i found a solution the .pem discord site certificate was not installed on windows so it could not work. But without it installed the whole backdoor wont work which makes the program a bit useless because when someone clicks on the backdoor.exe it can not connect back to discord. so it would be kind if you figure out a solution to this or maybe there is another way i did not found pls write back so i can learn a few things.

**Comment by Jvr2022** [comment]
i am gonna take a look now at the problem

**Comment by bawsuser** [comment]
do you found anything so far despite its working with installing the .pem certificate of the discord site

**Comment by Jvr2022** [comment]
I am at the moment on vacation so I continue in 3 days

**Comment by Jvr2022** [comment]
I think I found the problem we are using a old discord.py version

**Comment by bawsuser** [comment]
still not working this way but installing the discord .pem certificate made it is there a way of integrating this into the script ?

**Comment by bawsuser** [comment]
this lines of code helped my own bot with this problem

dependencies:
pip3 install certifi
 
import certifi

# Set SSL_CERT_FILE environment variable
os.environ['SSL_CERT_FILE'] = certifi.where()

**Comment by bawsuser** [comment]
by the way there is an unindented block on line 460 in your pinkcord.py in the template folder

**Comment by Jvr2022** [comment]
Oh I am gonna take a look into it

**Comment by Jvr2022** [comment]
The client login bug is fixed only you need to reinstall discord.py

**Comment by bawsuser** [comment]
Did you tested it on a windows virtual machine cause i still can not run your version of the fix but my fix works.

**Comment by Jvr2022** [comment]
I never tested it in a vm

**Comment by Jvr2022** [comment]
I am gonna Implement youre change soon

**Comment by Jvr2022** [comment]
stop we are still working on this
